[google_service_account]
type = "service_account"
project_id = "streamlit-crm-476923"
private_key_id = "e3767e7fe0f0ba40608bd57ed5db20420c90cb53"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC8Y1ZTHgRsGSvC\nsb0fTguigGbXAuinqht2nKmDFyBy0PZ4UxWxUWpByInABFg7FKAmNFYtuTaUi8iv\nIZEXVQJRs0QDuuocKt3Y/7YqLn5HApLqp+sSD4UMzTjYPsHWbX9lDBpzQoUoRG2c\nzmKMPc4OiXDn/qLYK/XDeKU3MoRJTKdLxuGyoqDo+j8OF3cZthOFy5N3JqgmSkka\nr7N3pD7d94NVFJo44DNyMw0b47ynXU1tR7Y60mxtNdbSMv8CRP0zloy0hY6TpBfe\nnOe4BQ8yZybDf6S/HVT6QA1g8zidpG/UdXEauix7Vsx1w+1aSjOY0f49a+F+s6Fi\n8fR2IjxpAgMBAAECggEAFVo0hvn2Yhq1wizjXNSbnrzrOxhQLq3KDFb8Ixi4U68x\n2mg/Y5BQ6Pkd/Nq5NeQT9VSWBntxT2OrGMeHEpQO7dvx2/Lf9VaZ+84a83u+0hVd\nedWTwCGscMujc2YkkgVp7LXzGwiJf2uHGYBufMsGC5GCL7dltXcBFXlbj46tHgIN\nXxpGB6jGHB0CnH1i94GQR3f0XSthCzJ4nlfKgFJKustCCj1diufBKr+X/G56Hc9w\nmQSdMRYtk2ZGI7HNK1gABzuIlcBh4OjKH8r7LOk3FHD1CXHKCyr8JjI8x8PYdhFW\nCnJ0YEaJb8YEgM6QYFPG0n1RQeup6RGGbO/XwdKokQKBgQDtT/hnoItrsspUYt2F\nUtfEZWp8xOflyt1WhrV9tuPvMCsNsRk4QxBMh/jsydCO7Vq4vEgShaLwsINvCgGl\nlYUTnmfeBpxSeTFrNmY87QtqcmkP+ZtFabmjKSRtJ8Dd2UkKfcy2wrrDh1pcLt/z\nptxu08P9ovoRQ8jIM69pN+0ucQKBgQDLORc85VD2wkX3NHpNa1T97vRmiABqckqq\nvIblUuw98cUbdljHJiH96SMDvr6HsDHTMmkn0BJTapNGWV04zMxXSiTyxznI4In6\ns46bQOVsHvFcGke200D8yCfUw1tiYdUhaNslSPYt6RfFiHNv0NRf49AeZcLUiwNV\nwS/VBQJZeQKBgBXMdsDuGmB2N+ewfTC1/2Pm/PUhETwmelZsYVd+6UkbX5kOX4av\nglvFUbROhX3bh63YfbZV2DXLwQb+IFCZf3Ph5SCb8tgQkd2LTbDjBV1tzQDOqNij\ncY3vRY1RTYITZ4YzMA7JrGYxlLdLBv9WoID9qs8tnVLgqxzYwpAjtwHBAoGAPQjp\nfMWWmnXgk400Sjo5LYbt6jlgfpfS6xJyJT/Rag1J2KSjpzRBs0Oo24AXMyNs43RZ\ndracOmdg0hkW0W9Y08KV9EB3j2g4qI3y/5fvD5j/flz6OuOZuhHXPKRrttGRNFaM\nstcF8OX32MDRgryifCYspGSFrlYN61x5JC479WkCgYEAlhLP0q1nqfomt+9wSMG1\nuABG3XkaUnfaLtDQemrhLf0F/2Ozb47kV0h3VcAoBq/NN+FhdxsTRycjJdwy498+\nA1nRGhx+LuzNXjW/XDzJ5c2qO99x4qVMpO6iP8HZQ6Z51YvrThGvS5cfx5D3MxeY\nnr2/0g1fikKZdBUTiuIj2CI=\n-----END PRIVATE KEY-----\n"
client_email = "streamlit-crm@streamlit-crm-476923.iam.gserviceaccount.com"
client_id = "101780742719944390801"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-crm%40streamlit-crm-476923.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[sheets]
SHEET_ID = "1psMM-yc8pP_4BzeeSTCGsKodJMTEkj5yZlnOTI51y6I"

[auth]
username = "Andr√©"
password = "230398"

